[server]
ip = "127.0.0.1"
port = 23456
trig_mode = 3
timeout_ms = 60000
exit_opt = 0

[mysql]
port = 3306
user = "root"
password = "modao"
database = "webserver"

[option]
connpool_num = 12
threadpool_num = 6
log_opt = 1
log_level = 0
log_queue_size = 0

[resources]
src = "/resources"
